# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: wiselinux-kde
description: Esta é minha imagem personalizada do KDE.
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Módulos customizados locais
  - type: base
    source: local

  - type: virtualization
    source: local

  - type: flatpak
    source: local

  - type: signing
