# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: wiselinux-kde
description: Esta é minha imagem personalizada do KDE.
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - from-file: packages/base.yml
  - from-file: packages/virtualization.yml
  - from-file: packages/flatpak.yml

  - type: signing
