---
# yaml-language-server: $schema=https://schema.blue-build.org/module-v1.json

type: dnf

repos:
  cleanup: true

install:
  packages:
    - micro
    - btrfs-assistant
    - libreswan
    - strongswan
    - NetworkManager-libreswan
    - NetworkManager-strongswan
    - plasma-nm-openswan

remove:
  packages:
    - firefox
    - firefox-langpacks
    - kwrite


type: dnf
group-install:
  with-optional: true
  packages:
      - networkmanager-submodules
    
